language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_install:
  - "yarn install"

jobs:
  include:
    - stage: test
      script: yarn test
    - stage: build
      script: yarn build
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        email: $EMAIL
        on:
          branch: master
          tags: false
        skip_cleanup: true
